# prefernces
font_family             UbuntuNerdFont
background              #000
font_size               11.0
shell                   /bin/zsh 
hide_window_decorations yes
copy_on_select          yes
enabled_layouts         grid

#windows
map alt+right           next_window
map alt+left            previous_window
map ctrl+alt+left       previous_tab
map ctrl+alt+right      next_tab
map ctrl+shift+left     resize_window narrower
map ctrl+shift+right    resize_window wider
window_border_width     0.5pt
draw_minimal_borders    yes
active_border_color     #1e1e2e
inactive_border_color   #1e1e2e

#tab bar
map alt+1               goto_tab 1
map alt+2               goto_tab 2
map alt+3               goto_tab 3
map alt+4               goto_tab 4
map alt+5               goto_tab 5
map alt+6               goto_tab 6
map alt+7               goto_tab 7
map alt+8               goto_tab 8
map alt+9               goto_tab 9
tab_switch_strategy     right
tab_bar_align           left
tab_bar_style           separator
tab_bar_margin_width    0
tab_bar_margin_height   0 10
# tab_bar_margin_color    #1e1e2e
tab_separator           "    "
tab_bar_edge            bottom
tab_bar_min_tabs        2
active_tab_font_style   normal
inactive_tab_font_style normal

#colors
tab_bar_background      #1e1e2e
active_tab_background   #1e1e2e
inactive_tab_background #1e1e2e
active_tab_foreground   #0ff
inactive_tab_foreground #8a8a8a

tab_title_template "{fmt.fg.red}{index} {fmt.fg.tab}{title.split('/')[-1]}"

