# prefernces
font_family             UbuntuNerdFont
background              #000
font_size               11.0
shell                   /bin/zsh 
hide_window_decorations yes
copy_on_select          yes
enabled_layouts         grid

#windows
map alt+2               next_window
map alt+1               previous_window
window_border_width     0.5pt
draw_minimal_borders    yes
active_border_color     #1e1e2e
inactive_border_color   #1e1e2e

#tab bar
tab_bar_style           separator
tab_bar_margin_width    6
tab_bar_margin_height   0 6
tab_separator           "   "
tab_bar_edge            bottom
tab_bar_min_tabs        2
active_tab_font_style   normal
inactive_tab_font_style normal

#colors
tab_bar_background      #000
active_tab_background   #000
inactive_tab_background #000
active_tab_foreground   #0ff
inactive_tab_foreground #8a8a8a

tab_title_template "{fmt.fg.tab}{title.split('/')[-1]}"

