# keybinds
unbind      C-b
bind        `       last-window
bind        e       send-prefix
bind        /       split-window -h -c "#{pane_cur rent_path}"
bind        -       split-window -v -c "#{pane_current_path}"
bind        w       kill-pane
bind        n       new-window -c ~

# preferences
set -g      default-shell                   "/usr/bin/zsh"
set -g      mouse                           on
set -s      escape-time                     1
set -g      status-interval                 1
set -g      base-index                      1
set -g      prefix                          `
set -g      renumber-windows                on
set -g      history-limit                   5000

# colors
set -g      status-style                    bg=#1e1e2e
set -g      pane-border-style               fg=#1e1e2e
set -g      pane-active-border-style        fg=#1e1e2e

# status bar #(pwd="#{pane_current_path}"; echo ${pwd####*/})
set -g      window-status-current-format    ' #[fg=#ff0000]#I#[fg=#8a8a8a]:#[fg=#00ffff]#{pane_current_command} '
set -g      window-status-format            ' #[fg=#ff0000]#I #[fg=#8a8a8a]#{pane_current_command} '
set -g      status-left                     ''
set -g      status-right                    ' #[fg=#8a8a8a]%d-%a Week-%V #[fg=#ff0000]%I:%M '