set -g      default-shell       "/bin/zsh"
set -g      mouse               on
set -s      escape-time         1
set -g      status-interval     1
set -g      base-index          1
set -g      prefix              `

unbind      C-b
bind-key    `       last-window
bind-key    e       send-prefix

bind    /   split-window    -h  -c  "#{pane_current_path}"
bind    -   split-window    -v  -c  "#{pane_current_path}"
bind    w   confirm-before  -p      "Kill current pane? (y/n) " kill-pane
bind    n   new-window      -c      ~

set -g  status-style                    bg=#000000
set -g  window-status-current-format    ' #[fg=#ff0000]#I#[fg=#8a8a8a]:#[fg=#eeeeee]#(pwd="#{pane_current_path}"; echo ${pwd####*/}) '
set -g  window-status-format            ' #[fg=#ff0000]#I #[fg=#8a8a8a]#(pwd="#{pane_current_path}"; echo ${pwd####*/})#[fg=#8a8a8a]#F '
set -g  status-left                     ''
set -g  status-right                    '#[fg=#8a8a8a]Week %V #[fg=#ff0000]%I:%M '
set -g  pane-border-style               fg=#1e1e2e
set -g  pane-active-border-style        fg=#1e1e2e

set -g  history-limit                   5000

