# preferences
set -g      default-shell       "/bin/zsh"
set -g      mouse               on
set -s      escape-time         1
set -g      status-interval     1
set -g      base-index          1
set -g      prefix              `
set -g      renumber-windows    on
set -g      history-limit       5000

# keybinds
unbind      C-b
bind-key    `       last-window
bind-key    e       send-prefix
bind-key    /       split-window    -h  -c  "#{pane_cur rent_path}"
bind-key    -       split-window    -v  -c  "#{pane_current_path}"
bind-key    w       kill-pane
bind-key    n       new-window      -c      ~

# user defined
bind-key    -n      M-1         select-pane -L
bind-key    -n      M-2         select-pane -R
bind-key    -nr     S-M-Left    resize-pane -L 5
bind-key    -nr     S-M-Right   resize-pane -R 5
bind-key    -nr     M-right     next-window
bind-key    -nr     M-left      previous-window

# colors
set -g      status-style                    bg=#000000
set -g      pane-border-style               fg=#1e1e2e
set -g      pane-active-border-style        fg=#1e1e2e

# status bar
set -g      window-status-current-format    ' #[fg=#ff0000]#I#[fg=#8a8a8a]:#[fg=#eeeeee]#(pwd="#{pane_current_path}"; echo ${pwd####*/}) '
set -g      window-status-format            ' #[fg=#ff0000]#I #[fg=#8a8a8a]#(pwd="#{pane_current_path}"; echo ${pwd####*/})#[fg=#8a8a8a]#F '
set -g      status-left                     ''
set -g      status-right                    ' #[fg=#8a8a8a]%d-%a Week-%V #[fg=#ff0000]%I:%M '


